name: CMake project build all platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
    build_linux:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v3
            with:
              persist-credentials: false
              ref: ${{ github.event.inputs.checkoutRef }}

          - name: Configure CMake
            run: cmake -B build_linux -S . -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

          - name: Build project
            run: cmake --build build_linux --config ${BUILD_TYPE}

          - name: Export build artifacts
            uses: actions/upload-artifact@v2
            with:
              name: build_linux
              path: build_linux

    build_windows:
        runs-on: windows-2019

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v3
            with:
              persist-credentials: false
              ref: ${{ github.event.inputs.checkoutRef }}

          - name: Set up CMake
            uses: microsoft/setup-msbuild@v1

          - name: Configure CMake
            run: cmake -B build_windows -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019"

          - name: Build project
            run: cmake --build build_windows --config Release

          - name: Export build artifacts
            uses: actions/upload-artifact@v2
            with:
              name: build_windows
              path: build_windows

    build_macos:
        runs-on: macos-latest

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v3
            with:
              persist-credentials: false
              ref: ${{ github.event.inputs.checkoutRef }}

          - name: Configure CMake
            run: cmake -B build_macos -S . -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

          - name: Build project
            run: cmake --build build_macos --config ${BUILD_TYPE}

          - name: Export build artifacts
            uses: actions/upload-artifact@v2
            with:
              name: build_macos
              path: build_macos