name: CMake project build all platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
    build_linux:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v3
            with:
              persist-credentials: false
              ref: ${{ github.event.inputs.checkoutRef }}

          - name: Set up CMake
            uses: actions/setup-cmake@v2
            with:
              cmake-version: '3.20.0'

          - name: Build on Linux
            run: cmake -B build_linux -S . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && cmake --build build --config ${BUILD_TYPE}

    build_windows:
        runs-on: windows-latest

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v3
            with:
              persist-credentials: false
              ref: ${{ github.event.inputs.checkoutRef }}

          - name: Set up CMake
            uses: actions/setup-cmake@v2
            with:
              cmake-version: '3.20.0'

          - name: Build on Windows
            run: cmake -B build_windows -S . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && cmake --build build --config ${BUILD_TYPE}

    build_macos:
        runs-on: macos-latest

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v3
            with:
              persist-credentials: false
              ref: ${{ github.event.inputs.checkoutRef }}

          - name: Set up CMake
            uses: actions/setup-cmake@v2
            with:
              cmake-version: '3.20.0'

          - name: Build on MacOS
            run: cmake -B build_macos -S . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && cmake --build build --config ${BUILD_TYPE}

    export_artifacts:
        runs-on: ubuntu-latest

        needs: [build_linux, build_windows, build_macos]

        steps:
          - name: Create zip file
            run: |
              mkdir build
              cp -r build_linux build/linux
              cp -r build_windows build/windows
              cp -r build_macos build/macos
              zip -r build.zip build
          - name: Upload artifacts
            uses: actions/upload-artifact@v2
            with:
                name: build-artifacts
                path: build