name: CMake project build all platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.checkoutRef }}

      - name: Install Qt6
        run: sudo apt-get install qt6-default

      - name: Configure CMake
        run: cmake -B build_linux -S . -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

      - name: Build project
        run: cmake --build build_linux --config ${BUILD_TYPE}

      - name: Export build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_linux
          path: build_linux

  build_windows:
    runs-on: windows-2019

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.checkoutRef }}

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install Qt6
        run: choco install qt6 --params '"/NoDesktopShortcut /NoStartMenuShortcut"'

      - name: Configure CMake
        run: cmake -B build_windows -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019"

      - name: Build project
        run: cmake --build build_windows --config Release

      - name: Export build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_windows
          path: build_windows

  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.checkoutRef }}

      - name: Install Qt6
        run: brew install qt@6

      - name: Configure CMake
        run: cmake -B build_macos -S . -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

      - name: Build project
        run: cmake --build build_macos --config ${BUILD_TYPE}

      - name: Export build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_macos
          path: build_macos
